unstable_features = true
indent_style = "Block"
use_small_heuristics = false
binop_separator = "Front"
combine_control_expr = true
control_brace_style = "AlwaysSameLine"
fn_args_density = "Tall"
brace_style = "SameLineWhere"
empty_item_single_line = true
fn_single_line = true
where_single_line = false
format_strings = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
merge_imports = true
match_block_trailing_comma = true
max_width = 80
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
reorder_impl_items = false
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 0
spaces_around_ranges = false
spaces_within_parens_and_brackets = false
struct_lit_single_line = true
force_multiline_blocks = true
tab_spaces = 4
hard_tabs = false
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
match_arm_blocks = true
write_mode = "Overwrite"
blank_lines_upper_bound = 1
remove_blank_lines_at_start_or_end_of_block = true